### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by hyomiTheTech** [WebXDAO/start-here#208]
### Name

David Kim

### Discord Username (if applicable)

David Kim#6905

### Additional Context

Hi guys! My name is David Kim, and I live in Las Vegas right now. I was originally worked in Finance/Accounting industry. But my investment in Cryptocurrency was a huge turning point in my life that led me to change my career to the tech industry as a coder, and I love it! I was a Front-end developer in my previous experience, but I can also code in the back-end. And I am learning solidity and doing a couple of solidity tutorials as well : ) I am super excited to join this community!

**Comment by mkubdev** [comment]
Welcome here @hyomiTheTech 🎉
