### ISSUE TITLE
[BUG] Minor typo in readme

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/start-here#227]
### Description of the bug

There's a minor typo in the readme file that should be fixed.

**Steps to follow**

1. Fork the repository [**here**](https://github.com/WebXDAO/start-here/fork).
2. Make a new branch named `fix_typo`. If you don't know how to create GitHub branches, see [**this article**](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches).
3. Go to the readme file, and edit it.
4. Replace line 8 with the following content:

```markdown
- Raise an [issue](https://github.com/WebXDAO/start-here/issues/new?assignees=&labels=github-invitation&template=invitation.yml&title=Please+invite+me+to+the+community) to get an invite to join the **WebXDAO** community.
```

5. Now make a pull request [**here**](https://github.com/WebXDAO/start-here/compare).
6. Click on the `Compare across forks` text to compare with your fork.
7. Select your repository as the head repository, then select the branch.
8. Click on the big green button that says `Create a pull request`.
9. That's it! You've successfully made a pull request.

### Add any other context about the problem here

This is a good first issue. Please leave it open for first-timers and beginners.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanishqr-ck** [comment]
Please assign me this issue

**Comment by shuklaritvik06** [comment]
> Please assign me this issue

Assigned to you!
