### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by prabhpreet-code** [WebXDAO/start-here#263]
### Name

Prabhpreet Singh

### Discord Username (if applicable)

prabhpreet singh#8303

### Additional Context

It's always a pleasure to work and learn with like-minded folks across the globe. I always wanted to work, learn and grow with such a web3 enthusiastic organization. It would be an honor to help someone in any way I could along with learning from the best minds in the world.

**Comment by shuklaritvik06** [comment]
Hey 👋🏼  Thanks for joining :) We are happy to have you in our community :)
