### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by yashdev9274** [WebXDAO/start-here#314]
### Name

Yash Dewasthale

### Discord Username (if applicable)

Yash Dewasthale#0154

### Additional Context

I'm a 3rd year Btech Electrical Engineering student from Madhav Institute of Technology & Science college.
My current goal is to  start my own cloud service based startup which will provide our client great analysis and cloud services for their business .
I'm currently learning DevOps/cloud engineering and data science skills which will help me in my startup journey.
I'm a good team leader, I have skills a leaders must have in them , which helps me to work with my team member affectively and can bring best from my teammates.

**Comment by mkubdev** [comment]
Welcome @yashdev9274 ✌️

**Comment by yashdev9274** [comment]
Thank you so much Max.
