### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by AnthonyByansi** [WebXDAO/start-here#351]
### Name

Anthony Byansi

### Discord Username (if applicable)

Anthony-Shafer 

### Additional Context

I meet WebXDAO through a friend. well its a community of self driven  people willing to make the world a better place through open source

**Comment by AnthonyByansi** [comment]
super excited to be part of you all

**Comment by mkubdev** [comment]
Hi @AnthonyByansi ! Welcome here :D !
